name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: rustup target add wasm32-unknown-unknown
    - uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - name: Build
      run: cargo build --all-features
      env:
          RUST_BACKTRACE: 1
    - name: Run tests
      run: cargo test
      env:
          RUST_BACKTRACE: 1
    - name: Check formatting
      run: cargo fmt -- --check